# decrypt deployment private key
before_install:
  - openssl aes-256-cbc -K $encrypted_f3556f82c616_key -iv $encrypted_f3556f82c616_iv -in arborchurch-travis.enc -out arborchurch-travis -d
  - chmod 0600 arborchurch-travis

# only deploy the master branch
branches: 
  only:
    - master

# install hugo
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.51/hugo_extended_0.51_Linux-64bit.tar.gz
  - tar xzvf hugo_0.51_Linux-64bit.tar.gz

# build the site
script: 
  - cd site
  - ../hugo --baseURL=https://www.arborchurch.com/ --theme=arbor

# deploy it!
after_success:
  - rsync -cav -e 'ssh -i ../arborchurch-travis -o StrictHostKeyChecking=no' --progress public/ arborchurch@arborchurch.com:arborchurch.com

