backend:
  name: github
  branch: master
  repo: arborchurch/arbor-web
media_folder: "static/img/uploads"
publish_mode: editorial_workflow
public_folder: "/img/uploads"
collections:
  - name: "event"
    label: "Event"
    folder: "site/content/event"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Expiration Date", name: "expirydate", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Where", name: "where", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "news"
    label: "News"
    folder: "site/content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}"
    identifier_field: date
    fields:
      - {label: "Publish Date", name: "date", widget: "datetime"}
  - name: "messages"
    label: Messages
    label_singular: 'Message'
    folder: site/content/messages
    create: true
    nested:
      depth: 2
      summary: '{{path}}'
    fields:
      - {label: "Date", name: "date", widget: "datetime", hint: "The date on which the message was delivered."}
      - {label: "Series", name: "series", widget: "string", hint: "The series to which the message belongs. Use all lower case and replace spaces with dashes. Example: loving-like-jesus"}
      - {label: "Speaker", name: "speaker", widget: "string", hint: "The speaker who delivered the message. Example: Alison Acone"}
      - {label: "Podcast URL", name: "podcast", widget: "string", hint: "The URL to the MP3 file containing the podcast's audio. Example: https://arborchurchnw.org/podcast/loving-like-jesus-part-1.mp3"}
      - {label: "Podcast size (bytes)", name: "podcast_bytes", widget: "string", hint: "The size of the MP3 file in bytes. Example: 20938922"}
      - {label: "Podcast duration (MM:SS)", name: "podcast_duration", widget: "string", hint: "The duration of the audio file. Example: 45:32"}
      - {label: "YouTube ID", name: "youtube_id", widget: "string", hint: "The YouTube ID of the video version of the podcast; this is the part of the YouTube URL after v=. Example: dQw4w9WgXcQ"}
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }

